-- Postgres edition of migrations/0001_core.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table actors (
  id text PRIMARY KEY,
  kind text not null check (kind in ('human', 'agent', 'organization')),
  username text not null unique,
  display_name text not null,
  bio text,
  website text,
  created_at text not null default now()
);

create index actors_kind_idx on actors (kind);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
-- updated_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text not null,
  title text not null,
  body text not null,
  author_id text not null references actors (id),
  attribution text not null default 'human' check (attribution in ('human', 'agent', 'human-assisted-agent', 'agent-assisted-human', 'organization')),
  accepted_answer_id bigint,
  answer_count bigint not null default 0,
  created_at text not null default now(),
  updated_at text not null default now()
);

create index questions_created_idx on questions (created_at, id);

create index questions_author_idx on questions (author_id);

create index questions_unanswered_idx on questions (answer_count, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
-- updated_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint not null references questions (id) on delete cascade,
  author_id text not null references actors (id),
  attribution text not null default 'human' check (attribution in ('human', 'agent', 'human-assisted-agent', 'agent-assisted-human', 'organization')),
  body text not null,
  is_accepted bigint not null default 0,
  verified_count bigint not null default 0,
  valid_from text,
  valid_through text,
  is_stale bigint not null default 0,
  superseded_by bigint references answers (id),
  created_at text not null default now(),
  updated_at text not null default now()
);

create index answers_question_idx on answers (question_id, created_at);

create index answers_author_idx on answers (author_id);

create table tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text not null unique,
  name text not null,
  description text,
  question_count bigint not null default 0
);

create table question_tags (
  question_id bigint not null references questions (id) on delete cascade,
  tag_id bigint not null references tags (id) on delete cascade,
  primary key (question_id, tag_id)
);

create index question_tags_tag_idx on question_tags (tag_id, question_id);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text not null check (content_type in ('question', 'answer')),
  content_id bigint not null,
  actor_id text not null references actors (id),
  body text not null,
  comment text,
  created_at text not null default now()
);

create index revisions_content_idx on revisions (content_type, content_id, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id bigint not null references answers (id) on delete cascade,
  actor_id text not null references actors (id),
  result text not null check (result in ('pass', 'fail', 'partial')),
  method text,
  environment text,
  output_summary text,
  is_independent bigint not null default 1,
  created_at text not null default now()
);

create index verifications_answer_idx on verifications (answer_id, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table votes (
  actor_id text not null references actors (id),
  content_type text not null check (content_type in ('question', 'answer')),
  content_id bigint not null,
  value bigint not null check (value in (-1, 1)),
  created_at text not null default now(),
  primary key (actor_id, content_type, content_id)
);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text references actors (id),
  action text not null,
  target_type text,
  target_id text,
  metadata text,
  created_at text not null default now()
);

create index audit_events_actor_idx on audit_events (actor_id, created_at);

-- FTS5 table "questions_fts" (title, body) has no Postgres counterpart; it is replaced below.
-- create virtual table questions_fts using fts5 (
--   title,
--   body,
--   content = 'questions',
--   content_rowid = 'id',
--   tokenize = 'porter unicode61'
-- )
alter table questions add column if not exists search tsvector
  generated always as (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))) stored;
create index if not exists questions_search_idx on questions using gin (search);
-- query: where search @@ websearch_to_tsquery('english', ?) order by ts_rank_cd(search, websearch_to_tsquery('english', ?)) desc

-- TODO: trigger "questions_fts_ai": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger questions_fts_ai after insert on questions begin
--   insert into questions_fts (rowid, title, body) values (new.id, new.title, new.body);
-- end

-- TODO: trigger "questions_fts_ad": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger questions_fts_ad after delete on questions begin
--   insert into questions_fts (questions_fts, rowid, title, body)
--     values ('delete', old.id, old.title, old.body);
-- end

-- TODO: trigger "questions_fts_au": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger questions_fts_au after update on questions begin
--   insert into questions_fts (questions_fts, rowid, title, body)
--     values ('delete', old.id, old.title, old.body);
--   insert into questions_fts (rowid, title, body) values (new.id, new.title, new.body);
-- end

-- FTS5 table "answers_fts" (body) has no Postgres counterpart; it is replaced below.
-- create virtual table answers_fts using fts5 (
--   body,
--   content = 'answers',
--   content_rowid = 'id',
--   tokenize = 'porter unicode61'
-- )
alter table answers add column if not exists search tsvector
  generated always as (to_tsvector('english', coalesce(body, ''))) stored;
create index if not exists answers_search_idx on answers using gin (search);
-- query: where search @@ websearch_to_tsquery('english', ?) order by ts_rank_cd(search, websearch_to_tsquery('english', ?)) desc

-- TODO: trigger "answers_fts_ai": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger answers_fts_ai after insert on answers begin
--   insert into answers_fts (rowid, body) values (new.id, new.body);
-- end

-- TODO: trigger "answers_fts_ad": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger answers_fts_ad after delete on answers begin
--   insert into answers_fts (answers_fts, rowid, body) values ('delete', old.id, old.body);
-- end

-- TODO: trigger "answers_fts_au": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- create trigger answers_fts_au after update on answers begin
--   insert into answers_fts (answers_fts, rowid, body) values ('delete', old.id, old.body);
--   insert into answers_fts (rowid, body) values (new.id, new.body);
-- end
