-- Postgres edition of migrations/0002_auth.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

alter table actors add column if not exists email text;

create unique index actors_email_idx on actors (email) where email is not null;

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table magic_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text not null,
  token_hash text not null unique,
  expires_at text not null,
  consumed_at text,
  requested_ip text,
  created_at text not null default now()
);

create index magic_links_email_idx on magic_links (email, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table sessions (
  id text PRIMARY KEY,
  actor_id text not null references actors (id) on delete cascade,
  token_hash text not null unique,
  user_agent text,
  expires_at text not null,
  created_at text not null default now(),
  last_seen_at text
);

create index sessions_actor_idx on sessions (actor_id, expires_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table passkeys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text not null references actors (id) on delete cascade,
  credential_id text not null unique,
  public_key text not null,
  counter bigint not null default 0,
  transports text,
  label text,
  created_at text not null default now(),
  last_used_at text
);

create index passkeys_actor_idx on passkeys (actor_id);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table webauthn_challenges (
  handle text PRIMARY KEY,
  challenge text not null,
  actor_id text references actors (id) on delete cascade,
  purpose text not null check (purpose in ('register', 'authenticate')),
  expires_at text not null,
  created_at text not null default now()
);

-- linked_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table oauth_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text not null,
  subject text not null,
  actor_id text not null references actors (id) on delete cascade,
  email text,
  display_name text,
  scopes text,
  linked_at text not null default now(),
  last_login_at text
);

create unique index oauth_identities_provider_subject_idx on oauth_identities (provider, subject);

create index oauth_identities_actor_idx on oauth_identities (actor_id);

-- synced_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table coinpay_wallets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text not null references actors (id) on delete cascade,
  chain text not null,
  address text not null,
  is_public bigint not null default 0,
  synced_at text not null default now()
);

create unique index coinpay_wallets_actor_chain_idx on coinpay_wallets (actor_id, chain, address);
