-- Postgres edition of migrations/0003_write_path.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text not null check (content_type in ('question', 'answer')),
  content_id bigint not null,
  author_id text not null references actors (id),
  attribution text not null default 'human' check (attribution in ('human', 'agent', 'human-assisted-agent', 'agent-assisted-human', 'organization')),
  body text not null,
  is_deleted bigint not null default 0,
  created_at text not null default now()
);

create index comments_content_idx on comments (content_type, content_id, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text not null check (content_type in ('question', 'answer', 'comment')),
  content_id bigint not null,
  actor_id text not null references actors (id),
  reason text not null check (reason in ('spam', 'abusive', 'secret', 'wrong', 'duplicate', 'other')),
  detail text,
  state text not null default 'open' check (state in ('open', 'upheld', 'declined')),
  resolved_by text references actors (id),
  resolved_at text,
  created_at text not null default now()
);

create index flags_open_idx on flags (state, created_at);

create unique index flags_one_per_actor_idx on flags (content_type, content_id, actor_id);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table duplicate_links (
  question_id bigint PRIMARY KEY references questions (id) on delete cascade,
  canonical_id bigint not null references questions (id) on delete cascade,
  actor_id text not null references actors (id),
  created_at text not null default now()
);

create index duplicate_links_canonical_idx on duplicate_links (canonical_id);

alter table questions add column if not exists score bigint not null default 0;

alter table answers add column if not exists score bigint not null default 0;

alter table questions add column if not exists comment_count bigint not null default 0;
