-- Postgres edition of migrations/0005_reputation_moderation.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

alter table actors add column if not exists reputation bigint not null default 0;

alter table actors add column if not exists reputation_computed_at text;

create table actor_tag_reputation (
  actor_id text not null references actors (id) on delete cascade,
  tag_id bigint not null references tags (id) on delete cascade,
  reputation bigint not null default 0,
  primary key (actor_id, tag_id)
);

create index actor_tag_reputation_tag_idx on actor_tag_reputation (tag_id, reputation);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table moderation_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text not null check (content_type in ('question', 'answer', 'comment')),
  content_id bigint not null,
  actor_id text not null references actors (id),
  action text not null check (action in ('hide', 'restore', 'lock', 'unlock')),
  reason text,
  flag_id bigint references flags (id),
  created_at text not null default now()
);

create index moderation_actions_content_idx on moderation_actions (content_type, content_id, created_at);

alter table questions add column if not exists is_hidden bigint not null default 0;

alter table answers add column if not exists is_hidden bigint not null default 0;

alter table questions add column if not exists is_locked bigint not null default 0;
