-- Postgres edition of migrations/0006_canonical.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
-- updated_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table canonical_answers (
  question_id bigint PRIMARY KEY references questions (id) on delete cascade,
  body text not null,
  works_with text,
  known_exceptions text,
  state text not null default 'published' check (state in ('published', 'stale', 'superseded')),
  current_revision_id bigint,
  created_at text not null default now(),
  updated_at text not null default now()
);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table canonical_answer_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint not null references questions (id) on delete cascade,
  actor_id text not null references actors (id),
  body text not null,
  works_with text,
  known_exceptions text,
  comment text,
  created_at text not null default now()
);

create index canonical_revisions_question_idx on canonical_answer_revisions (question_id, created_at);

create table canonical_answer_sources (
  question_id bigint not null references questions (id) on delete cascade,
  answer_id bigint not null references answers (id) on delete cascade,
  primary key (question_id, answer_id)
);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table canonical_challenges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint not null references questions (id) on delete cascade,
  actor_id text not null references actors (id),
  reason text not null,
  state text not null default 'open' check (state in ('open', 'accepted', 'rejected')),
  resolved_by text references actors (id),
  resolved_at text,
  created_at text not null default now()
);

create index canonical_challenges_open_idx on canonical_challenges (question_id, state);
