-- Postgres edition of migrations/0007_notifications.sql, generated with `npx libsql-pg convert-schema`
-- (text timestamps kept as text) and reviewed. Applied by src/migrate.ts when DATABASE_URL is
-- postgres://; keep the two directories in step.

create table notification_preferences (
  actor_id text not null references actors (id) on delete cascade,
  type text not null,
  email bigint not null default 1,
  web bigint not null default 1,
  primary key (actor_id, type)
);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text not null references actors (id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  url text,
  actor_from text references actors (id),
  read_at text,
  emailed_at text,
  created_at text not null default now()
);

create index notifications_inbox_idx on notifications (actor_id, read_at, created_at);

create index notifications_pending_email_idx on notifications (emailed_at, created_at);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table watches (
  actor_id text not null references actors (id) on delete cascade,
  question_id bigint not null references questions (id) on delete cascade,
  created_at text not null default now(),
  primary key (actor_id, question_id)
);

create index watches_question_idx on watches (question_id);

-- created_at: default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -> now()
create table push_subscriptions (
  id text PRIMARY KEY,
  actor_id text not null references actors (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at text not null default now()
);

create index push_subscriptions_actor_idx on push_subscriptions (actor_id);
